name: Update Readme
on:
  workflow_dispatch:
  schedule:
    # Runs at 12am NZT
    - cron: '0 12 * * *'
      
jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_OS: False
          SHOW_EDITORS: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          
